/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_Window */

#ifndef _Included_android_view_Window
#define _Included_android_view_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_Window
 * Method:    set_widget_as_root
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1widget_1as_1root
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
