/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Canvas */

#ifndef _Included_android_graphics_Canvas
#define _Included_android_graphics_Canvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Canvas
 * Method:    native_contructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_native_1contructor
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Canvas
 * Method:    native_drawLine
 * Signature: (JFFFFLandroid/graphics/Paint;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_native_1drawLine
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
