/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_Activity */

#ifndef _Included_android_app_Activity
#define _Included_android_app_Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_app_Activity
 * Method:    set_widget_as_root
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_Activity_set_1widget_1as_1root
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
