/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_LinearLayout */

#ifndef _Included_android_view_LinearLayout
#define _Included_android_view_LinearLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_LinearLayout
 * Method:    native_constructor
 * Signature: (Landroid/util/AttributeSet;)V
 */
JNIEXPORT void JNICALL Java_android_view_LinearLayout_native_1constructor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_view_LinearLayout
 * Method:    addView
 * Signature: (Landroid/view/View;ILandroid/view/ViewGroup/LayoutParams;)V
 */
JNIEXPORT void JNICALL Java_android_view_LinearLayout_addView
  (JNIEnv *, jobject, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
