/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_launch_main */

#ifndef _Included_org_launch_main
#define _Included_org_launch_main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_launch_main
 * Method:    real_main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_launch_main_real_1main
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
