/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_ViewGroup */

#ifndef _Included_android_view_ViewGroup
#define _Included_android_view_ViewGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_ViewGroup
 * Method:    addView
 * Signature: (Landroid/view/View;ILandroid/view/ViewGroup/LayoutParams;)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewGroup_addView
  (JNIEnv *, jobject, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
