/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_MessageQueue */

#ifndef _Included_android_os_MessageQueue
#define _Included_android_os_MessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_MessageQueue
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_os_MessageQueue_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_os_MessageQueue_nativeDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativePollOnce
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_MessageQueue_nativePollOnce
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeWake
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_os_MessageQueue_nativeWake
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeIsIdling
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_MessageQueue_nativeIsIdling
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
