/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_drawable_BitmapDrawable */

#ifndef _Included_android_graphics_drawable_BitmapDrawable
#define _Included_android_graphics_drawable_BitmapDrawable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_drawable_BitmapDrawable
 * Method:    native_paintable_from_pixbuf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_BitmapDrawable_native_1paintable_1from_1pixbuf
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
