/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Path */

#ifndef _Included_android_graphics_Path
#define _Included_android_graphics_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Path
 * Method:    init1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Path_init1
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Path
 * Method:    init2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Path_init2
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_rewind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rewind
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_set
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1set
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_getFillType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Path_native_1getFillType
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_setFillType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1setFillType
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_isEmpty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1isEmpty
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_isRect
 * Signature: (ILandroid/graphics/RectF;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1isRect
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_graphics_Path
 * Method:    native_computeBounds
 * Signature: (ILandroid/graphics/RectF;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1computeBounds
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_graphics_Path
 * Method:    native_incReserve
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1incReserve
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_moveTo
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1moveTo
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rMoveTo
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rMoveTo
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_lineTo
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1lineTo
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rLineTo
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rLineTo
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_quadTo
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1quadTo
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rQuadTo
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rQuadTo
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_cubicTo
 * Signature: (IFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1cubicTo
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rCubicTo
 * Signature: (IFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rCubicTo
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_arcTo
 * Signature: (ILandroid/graphics/RectF;FFZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1arcTo
  (JNIEnv *, jclass, jint, jobject, jfloat, jfloat, jboolean);

/*
 * Class:     android_graphics_Path
 * Method:    native_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1close
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRect
 * Signature: (ILandroid/graphics/RectF;I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRect__ILandroid_graphics_RectF_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRect
 * Signature: (IFFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRect__IFFFFI
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addOval
 * Signature: (ILandroid/graphics/RectF;I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addOval
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addCircle
 * Signature: (IFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addCircle
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addArc
 * Signature: (ILandroid/graphics/RectF;FF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addArc
  (JNIEnv *, jclass, jint, jobject, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRoundRect
 * Signature: (ILandroid/graphics/RectF;FFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRoundRect__ILandroid_graphics_RectF_2FFI
  (JNIEnv *, jclass, jint, jobject, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addRoundRect
 * Signature: (ILandroid/graphics/RectF;[FI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addRoundRect__ILandroid_graphics_RectF_2_3FI
  (JNIEnv *, jclass, jint, jobject, jfloatArray, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__IIFF
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_addPath
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1addPath__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_offset
 * Signature: (IFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1offset__IFFI
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_offset
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1offset__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_setLastPoint
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1setLastPoint
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_transform
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1transform__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_transform
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1transform__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    native_op
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Path_native_1op
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Path
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_finalizer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
