/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_GskCanvas */

#ifndef _Included_android_graphics_GskCanvas
#define _Included_android_graphics_GskCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawBitmap
 * Signature: (JJIIIII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawBitmap
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_GskCanvas
 * Method:    native_drawRect
 * Signature: (JFFFFI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_GskCanvas_native_1drawRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
