/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_AlertDialog */

#ifndef _Included_android_app_AlertDialog
#define _Included_android_app_AlertDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_app_AlertDialog
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_app_AlertDialog_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetTitle
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetMessage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetMessage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetButton
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetButton
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetItems
 * Signature: (J[Ljava/lang/String;Landroid/content/DialogInterface/OnClickListener;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetItems
  (JNIEnv *, jobject, jlong, jobjectArray, jobject);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeShow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeShow
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
