/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Matrix */

#ifndef _Included_android_graphics_Matrix
#define _Included_android_graphics_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Matrix_MSCALE_X
#define android_graphics_Matrix_MSCALE_X 0L
#undef android_graphics_Matrix_MSKEW_X
#define android_graphics_Matrix_MSKEW_X 1L
#undef android_graphics_Matrix_MTRANS_X
#define android_graphics_Matrix_MTRANS_X 2L
#undef android_graphics_Matrix_MSKEW_Y
#define android_graphics_Matrix_MSKEW_Y 3L
#undef android_graphics_Matrix_MSCALE_Y
#define android_graphics_Matrix_MSCALE_Y 4L
#undef android_graphics_Matrix_MTRANS_Y
#define android_graphics_Matrix_MTRANS_Y 5L
#undef android_graphics_Matrix_MPERSP_0
#define android_graphics_Matrix_MPERSP_0 6L
#undef android_graphics_Matrix_MPERSP_1
#define android_graphics_Matrix_MPERSP_1 7L
#undef android_graphics_Matrix_MPERSP_2
#define android_graphics_Matrix_MPERSP_2 8L
/*
 * Class:     android_graphics_Matrix
 * Method:    native_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Matrix_native_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_isIdentity
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1isIdentity
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_rectStaysRect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1rectStaysRect
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_set
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1set
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setTranslate
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setTranslate
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setScale
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setScale__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setScale
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setScale__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRotate
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setRotate__IFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRotate
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setRotate__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSinCos
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSinCos__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSinCos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSinCos__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSkew
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSkew__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSkew
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSkew__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setConcat
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setConcat
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preTranslate
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preTranslate
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preScale
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preScale__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preScale
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preScale__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preRotate
 * Signature: (IFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preRotate__IFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preRotate
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preRotate__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preSkew
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preSkew__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preSkew
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preSkew__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preConcat
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preConcat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postTranslate
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postTranslate
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postScale
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postScale__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postScale
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postScale__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postRotate
 * Signature: (IFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postRotate__IFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postRotate
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postRotate__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postSkew
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postSkew__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postSkew
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postSkew__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postConcat
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postConcat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRectToRect
 * Signature: (ILandroid/graphics/RectF;Landroid/graphics/RectF;I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setRectToRect
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setPolyToPoly
 * Signature: (I[FI[FII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setPolyToPoly
  (JNIEnv *, jclass, jint, jfloatArray, jint, jfloatArray, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_invert
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1invert
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapPoints
 * Signature: (I[FI[FIIZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1mapPoints
  (JNIEnv *, jclass, jint, jfloatArray, jint, jfloatArray, jint, jint, jboolean);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapRect
 * Signature: (ILandroid/graphics/RectF;Landroid/graphics/RectF;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1mapRect
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapRadius
 * Signature: (IF)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_Matrix_native_1mapRadius
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_getValues
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1getValues
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setValues
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setValues
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_equals
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1equals
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_finalizer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
