/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Paint */

#ifndef _Included_android_graphics_Paint
#define _Included_android_graphics_Paint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Paint
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Paint_native_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_color
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1color
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_color
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1color
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
