/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_AudioTrack */

#ifndef _Included_android_media_AudioTrack
#define _Included_android_media_AudioTrack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_AudioTrack
 * Method:    native_constructor
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_android_media_AudioTrack_native_1constructor
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_media_AudioTrack
 * Method:    getMinBufferSize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_android_media_AudioTrack_getMinBufferSize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_media_AudioTrack
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_media_AudioTrack_play
  (JNIEnv *, jobject);

/*
 * Class:     android_media_AudioTrack
 * Method:    write
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_android_media_AudioTrack_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
