/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_database_CursorWindow */

#ifndef _Included_android_database_CursorWindow
#define _Included_android_database_CursorWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_database_CursorWindow
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_android_database_CursorWindow_nativeCreate
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_database_CursorWindow_nativeDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_database_CursorWindow_nativeGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetBlob
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_database_CursorWindow_nativeGetBlob
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetString
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_database_CursorWindow_nativeGetString
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeCopyStringToBuffer
 * Signature: (JIILandroid/database/CharArrayBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_database_CursorWindow_nativeCopyStringToBuffer
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativePutBlob
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativePutBlob
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativePutString
 * Signature: (JLjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativePutString
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_database_CursorWindow_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetNumRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_database_CursorWindow_nativeGetNumRows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeSetNumColumns
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativeSetNumColumns
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeAllocRow
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativeAllocRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeFreeLastRow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_database_CursorWindow_nativeFreeLastRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetType
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_android_database_CursorWindow_nativeGetType
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetLong
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_android_database_CursorWindow_nativeGetLong
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativeGetDouble
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_android_database_CursorWindow_nativeGetDouble
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativePutLong
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativePutLong
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativePutDouble
 * Signature: (JDII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativePutDouble
  (JNIEnv *, jclass, jlong, jdouble, jint, jint);

/*
 * Class:     android_database_CursorWindow
 * Method:    nativePutNull
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_database_CursorWindow_nativePutNull
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
