/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_gles_jni_EGLImpl */

#ifndef _Included_com_google_android_gles_jni_EGLImpl
#define _Included_com_google_android_gles_jni_EGLImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglCreateContext
 * Signature: (JJLjavax/microedition/khronos/egl/EGLContext;[I)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglCreateContext
  (JNIEnv *, jobject, jlong, jlong, jobject, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglChooseConfig
 * Signature: (J[I[JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglChooseConfig
  (JNIEnv *, jobject, jlong, jintArray, jlongArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
