/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_widget_TextView */

#ifndef _Included_android_widget_TextView
#define _Included_android_widget_TextView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_widget_TextView
 * Method:    native_constructor
 * Signature: (Landroid/util/AttributeSet;)V
 */
JNIEXPORT void JNICALL Java_android_widget_TextView_native_1constructor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_widget_TextView
 * Method:    setText
 * Signature: (Ljava/lang/CharSequence;)V
 */
JNIEXPORT void JNICALL Java_android_widget_TextView_setText
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
